on:
  push:
    branches:
    - main
    - dev
jobs:
  build-image-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: felegy/mirror-action@master
      with:
        REMOTE: git@${{ secrets.DEPLOY_REPO }}:${{ github.repository }}.git
        SSH_CONFIG: |
          Host ${{ secrets.DEPLOY_REPO }}
            ProxyCommand cloudflared access ssh --hostname %h
        GIT_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
