on:
  push:
    branches: [ main ]
jobs:
  build-image-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: https://git.saito.systems/felegy/test-php.git
        GIT_USERNAME: felegy
        GIT_PASSWORD: ${{ secrets.DEPLOY_REPO_TOKEN }}
